### ISSUE TITLE
Mac build under v2.4

### ISSUE THREAD

**Issue by robertladwig** [Eawag-AppliedSystemAnalysis/Simstrat#38]
I'm currently trying to build a UNIX executable using the recent version 2.4 for macOS. Here I'm having several questions and issues regarding the new addition of the progress bar using forbear.
The fobos script in /build for release-gnu-dynamic doesn't include `../lib/forbear/fobos:shared-gnu((direct))` in contrast to release-gnu. I guess that this was done intentionally in the last commit, but then the compilation of Simstrat.f90 won't work as `use forbear` fails. 

When adding that line to release-gnu-dynamic, I also changed the fobos in lib/forbear to include the option for template-shared-gnu which was deleted in the last commit. Still when trying to compile using `FoBiS.py build -mode release-gnu-dynamic` it fails. The error I get is related to the building of forbear (see below).  

Would it be possible that I can change my code that it won't use the progress bar feature, or is forbear now an essential part?

Thanks!
Robert

Compilation error:
`Building dependency fobos into ../lib/forbear with mode shared-gnu
Traceback (most recent call last):
  File "/Users/robertladwig/anaconda3/bin/FoBiS.py", line 4, in <module>
    __import__('pkg_resources').run_script('FoBiS.py==2.9.3', 'FoBiS.py')
  File "/Users/robertladwig/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/robertladwig/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/robertladwig/anaconda3/lib/python3.7/site-packages/FoBiS.py-2.9.3-py3.7.egg/EGG-INFO/scripts/FoBiS.py", line 21, in <module>
  File "/Users/robertladwig/anaconda3/lib/python3.7/site-packages/FoBiS.py-2.9.3-py3.7.egg/fobis/fobis.py", line 45, in main
  File "/Users/robertladwig/anaconda3/lib/python3.7/site-packages/FoBiS.py-2.9.3-py3.7.egg/fobis/fobis.py", line 58, in run_fobis
  File "/Users/robertladwig/anaconda3/lib/python3.7/site-packages/FoBiS.py-2.9.3-py3.7.egg/fobis/FoBiSConfig.py", line 65, in __init__
  File "/Users/robertladwig/anaconda3/lib/python3.7/site-packages/FoBiS.py-2.9.3-py3.7.egg/fobis/Fobos.py", line 76, in __init__
  File "/Users/robertladwig/anaconda3/lib/python3.7/site-packages/FoBiS.py-2.9.3-py3.7.egg/fobis/Fobos.py", line 238, in _set_cliargs
  File "/Users/robertladwig/anaconda3/lib/python3.7/site-packages/FoBiS.py-2.9.3-py3.7.egg/fobis/Fobos.py", line 176, in _check_local_variables
  File "/Users/robertladwig/anaconda3/lib/python3.7/site-packages/FoBiS.py-2.9.3-py3.7.egg/fobis/Fobos.py", line 144, in _get_local_variables
  File "/Users/robertladwig/anaconda3/lib/python3.7/configparser.py", line 857, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/Users/robertladwig/anaconda3/lib/python3.7/configparser.py", line 857, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "/Users/robertladwig/anaconda3/lib/python3.7/configparser.py", line 854, in <lambda>
    section, option, d[option], d)
  File "/Users/robertladwig/anaconda3/lib/python3.7/configparser.py", line 394, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/Users/robertladwig/anaconda3/lib/python3.7/configparser.py", line 444, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%^%forbear/%" -czf forbear.tar.gz *'`

**Comment by d-vanzo** [comment]
Hi Robert,
as you correctly pointed out, the main `fobos` file was not updated with regard to the dynamic compiling, now this is fixed in f7737546a23db2d83c8fd0dfd295aac6a4e39547
This compiles well with dynamic libraries on Linux system, I cannot test on macOS.

Regarding the other errors:
- as stated in the [README.md](https://github.com/Eawag-AppliedSystemAnalysis/Simstrat/blob/master/README.md), you need FoBiS 3.0.1 or later
- if you didn't do it, remember to delete the `forbear` subfolder and reinitialize the submodules  with the given script as explained in the  [README.md](https://github.com/Eawag-AppliedSystemAnalysis/Simstrat/blob/master/README.md)

Hope this helps

**Comment by robertladwig** [comment]
Hi Davide,

Thanks for the reply and sorry for my late answer. I had really used an older version of FoBiS in my pip environment (2.9 I think). After upgrading it and initializing the 3rd party libraries, I still get this error:

```
robertladwig$ FoBiS.py build -mode release-gnu-dynamic
Attention: the file './lib/forbear/src/lib/forbear_element_object.F90' depends on 'face' that is unreachable
Attention: the file './lib/json_fortran/src/json_value_module.F90' depends on 'ifcore' that is unreachable
Builder options
  Directories
    Building directory: "."
    Compiled-objects .o   directory: "obj"
    Compiled-objects .mod directory: "mod"
  Included paths: ./lib/json_fortran/src 
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building ./lib/forbear/src/tests/forbear_test.F90
Compiling ./lib/forbear/src/lib/forbear_kinds.F90 serially
Compiling ./lib/forbear/src/lib/forbear_element_object.F90 serially
./lib/forbear/src/lib/forbear_element_object.F90:6:4:

    6 | use face, only : colorize
      |    1
Fatal Error: Cannot open module file 'face.mod' for reading at (1): No such file or directory
compilation terminated.

./lib/forbear/src/lib/forbear_element_object.F90:6:4:

    6 | use face, only : colorize
      |    1
Fatal Error: Cannot open module file 'face.mod' for reading at (1): No such file or directory
compilation terminated.
```

which at least doesn't seem as severe as the one before. Forbear only created the file forbear_kinds.mod, which is called in forbear_element_objct.F90 at line 7, but not face.mod that is called a line earlier. In the forbear directories there's a third_party folder containing an empty folder called FACE. I'm a bit lost in how to fix this, but maybe that problem is also only me.
Is it possible that Forbear's 3rd party module weren't initialized in the right way?

Thanks,
Robert

**Comment by robertladwig** [comment]
After some tinkering, I added FACE to the .gitmodules
` git submodule add https://github.com/szaghi/FACE`
initialized and ran FoBiS again.

Now the FACE and forbear compilation worked without problems, but I got Simstrat-specific errors like: 

` Compiling ./lib/json_fortran/src/json_module.F90 ./src/strat_forcing.f90 serially
./src/strat_forcing.f90:47:132:
   47 |       if(self%cfg%snow_model == 1) call warn('The snow module is turned on. This module needs precipitation data, note that the last column in the forcing file will be interpreted as precipitation.')
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:47:45: `

or

`  520 |          state%albedo_data(3,1:12) = [0.064_RK, 0.064_RK, 0.068_RK, 0.076_RK, 0.089_RK, 0.097_RK, 0.091_RK, 0.079_RK, 0.070_RK, 0.065_RK, 0.064_RK, 0.064_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:521:132:`

**Comment by d-vanzo** [comment]
Hi @robertladwig , for the FACE lib, your workaround is ok, but I guess you just need to recursively initialize/update the submodule (and not adding all the nested submodules to .gitmodules)
Something like: `git submodule update --init --recursive`

For the second error I have no clues in this moment, maybe @Diftin has suggestions.
In case I can have a look, but not earlier than late next week.

**Comment by robertladwig** [comment]
After digging around, I think my issue is similar to this https://stackoverflow.com/questions/34194589/line-truncated-syntax-error-in-argument-list. My gfortran compiler truncates the input lines and afterwards I get incomplete lines.

**Comment by robertladwig** [comment]
After digging around, I think my issue is similar to this https://stackoverflow.com/questions/34194589/line-truncated-syntax-error-in-argument-list. My gfortran compiler truncates the input lines and afterwards I get incomplete lines.

But this shouldn't happen, right? Because in fobos you state that
`cflags=-c -O2 -std=f2008 -ffree-line-length-none`

**Comment by Diftin** [comment]
Hi @robertladwig,

Sorry for my late response, I was on holidays.

Indeed, I can reproduce your errors in strat_forcing.f90 if I remove the compiling flag "-ffree-line-length-none".
I can see above that you use the compiling mode "release-gnu-dynamic" but you only have "c" as compiling flag:
`Compiling flags: "-c" `

However, this should read
`cflags=-c -O2 -std=f2008 -ffree-line-length-none`
according to the current fobos in the master.

So just add the -free-line-length-none flag to the compiling mode you are using and you should be fine.

**Comment by robertladwig** [comment]
Hi @Diftin,

I'm at loss why it's using` Compiling flags: "-c",` probably because in the fobos for forbear and FACE it's only given ` -cpp -c -frealloc-lhs `.

I'm running the default fobos in build using mode release-gnu-dynamic that includes

```
[release-gnu-dynamic]
compiler=Gnu
cflags=-c -O2 -std=f2008 -ffree-line-length-none
lflags=-dynamic-libgcc -dynamic-libgfortran -dynamic
build_dir=.
src=../src/
colors=False
quiet=False
target=simstrat.f90
dependon=../lib/csv_fortran/fobos:release-gnu((direct))
         ../lib/json_fortran/fobos:release-gnu((direct))
         ../lib/forbear/fobos:static-gnu((direct))
log=True
```

Any idea why it's not applying the `-ffree-line-length-none` argument?

**Comment by robertladwig** [comment]
I'm running 
`git submodule update --init --recursive
./git_lib_initialize.sh
FoBiS.py build -mode release-gnu-dynamic`

and get
```
robertladwig$ FoBiS.py build -mode release-gnu-dynamic
Attention: the file './lib/json_fortran/src/json_value_module.F90' depends on 'ifcore' that is unreachable
Builder options
  Directories
    Building directory: "."
    Compiled-objects .o   directory: "obj"
    Compiled-objects .mod directory: "mod"
  Included paths: ./lib/json_fortran/src 
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building ./lib/forbear/src/tests/forbear_test.F90
Compiling ./lib/forbear/src/third_party/FACE/src/lib/face.F90 ./lib/forbear/src/lib/forbear_kinds.F90 serially
Compiling ./lib/forbear/src/lib/forbear_element_object.F90 serially
Compiling ./lib/forbear/src/lib/forbear_bar_object.F90 serially
Compiling ./lib/forbear/src/lib/forbear.f90 serially
Compiling ./lib/forbear/src/tests/forbear_test.F90 serially
Linking ./forbear_test
Target ./lib/forbear/src/tests/forbear_test.F90 has been successfully built
Builder options
  Directories
    Building directory: "."
    Compiled-objects .o   directory: "obj"
    Compiled-objects .mod directory: "mod"
  Included paths: ./lib/json_fortran/src 
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building ./lib/forbear/src/third_party/FACE/src/tests/face_test_basic.f90
Compiling ./lib/forbear/src/third_party/FACE/src/tests/face_test_basic.f90 serially
Linking ./face_test_basic
Target ./lib/forbear/src/third_party/FACE/src/tests/face_test_basic.f90 has been successfully built
Builder options
  Directories
    Building directory: "."
    Compiled-objects .o   directory: "obj"
    Compiled-objects .mod directory: "mod"
  Included paths: ./lib/json_fortran/src 
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building ./lib/forbear/src/third_party/FACE/src/tests/face_test_ucs4.F90
Compiling ./lib/forbear/src/third_party/FACE/src/tests/face_test_ucs4.F90 serially
Linking ./face_test_ucs4
Target ./lib/forbear/src/third_party/FACE/src/tests/face_test_ucs4.F90 has been successfully built
Builder options
  Directories
    Building directory: "."
    Compiled-objects .o   directory: "obj"
    Compiled-objects .mod directory: "mod"
  Included paths: ./lib/json_fortran/src 
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building ./lib/forbear/src/third_party/FACE/src/tests/face_test_colors.f90
Compiling ./lib/forbear/src/third_party/FACE/src/tests/face_test_colors.f90 serially
Linking ./face_test_colors
Target ./lib/forbear/src/third_party/FACE/src/tests/face_test_colors.f90 has been successfully built
Builder options
  Directories
    Building directory: "."
    Compiled-objects .o   directory: "obj"
    Compiled-objects .mod directory: "mod"
  Included paths: ./lib/json_fortran/src 
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building ./lib/forbear/src/third_party/FACE/src/tests/face_test_styles.f90
Compiling ./lib/forbear/src/third_party/FACE/src/tests/face_test_styles.f90 serially
Linking ./face_test_styles
Target ./lib/forbear/src/third_party/FACE/src/tests/face_test_styles.f90 has been successfully built
Builder options
  Directories
    Building directory: "."
    Compiled-objects .o   directory: "obj"
    Compiled-objects .mod directory: "mod"
  Included paths: ./lib/json_fortran/src 
  Compiler options
    Vendor: "gnu"
    Compiler command: "gfortran"
    Module directory switch: "-J"
    Compiling flags: "-c"
    Linking flags: ""
    Preprocessing flags: ""
    Coverage: False
    Profile: False
  Preprocessor used: None
  Preprocessor output directory: None
  Preprocessor extensions processed: []

Building ./src/simstrat.f90
Compiling ./src/strat_kinds.f90 serially
Compiling ./src/utilities.f90 serially
Compiling ./src/strat_grid.f90 ./src/strat_consts.f90 serially
Compiling ./src/strat_simdata.f90 serially
Compiling ./lib/json_fortran/src/json_kinds.F90 serially
Compiling ./lib/json_fortran/src/json_parameters.F90 ./lib/csv_fortran/src/csv_kinds.f90 ./src/strat_discretization.f90 ./src/strat_solver.f90 serially
Compiling ./lib/json_fortran/src/json_string_utilities.F90 ./lib/csv_fortran/src/csv_parameters.f90 ./src/strat_statevar.f90 serially
Compiling ./lib/json_fortran/src/json_value_module.F90 ./lib/csv_fortran/src/csv_utilities.f90 serially
Compiling ./lib/json_fortran/src/json_file_module.F90 ./lib/csv_fortran/src/csv_module.F90 serially
Compiling ./lib/json_fortran/src/json_module.F90 ./src/strat_forcing.f90 serially
./src/strat_forcing.f90:47:132:

   47 |       if(self%cfg%snow_model == 1) call warn('The snow module is turned on. This module needs precipitation data, note that the last column in the forcing file will be interpreted as precipitation.')
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:47:45:

   47 |       if(self%cfg%snow_model == 1) call warn('The snow module is turned on. This module needs precipitation data, note that the last column in the forcing file will be interpreted as precipitation.')
      |                                             1
Error: Missing ')' in statement at or before (1)
./src/strat_forcing.f90:281:132:

  281 |                fu = sqrt((2.7_RK*max(0.0_RK,(T_surf-state%T_atm)/(1 - 0.378_RK*Vap_atm/param%p_air))**0.333_RK)**2 + (0.6072_RK*3.1_RK*state%uv10)**2)
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:281:132:

  281 |                fu = sqrt((2.7_RK*max(0.0_RK,(T_surf-state%T_atm)/(1 - 0.378_RK*Vap_atm/param%p_air))**0.333_RK)**2 + (0.6072_RK*3.1_RK*state%uv10)**2)
      |                                                                                                                                    1
Error: Missing kind-parameter at (1)
./src/strat_forcing.f90:358:132:

  358 |                state%heat = F_glob * exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h) * param%beta_sol
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:358:132:

  358 |                state%heat = F_glob * exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h) * param%beta_sol
      |                                                                                                                                    1
Error: Syntax error in argument list at (1)
./src/strat_forcing.f90:359:132:

  359 |                state%rad0 = F_glob * exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h) * (1 - param%beta_sol)
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:359:132:

  359 |                state%rad0 = F_glob * exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h) * (1 - param%beta_sol)
      |                                                                                                                                    1
Error: Syntax error in argument list at (1)
./src/strat_forcing.f90:365:132:

  365 |                F_snowice = F_glob * (exp(-lambda_snow*state%snow_h) - exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h))
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:365:132:

  365 |                F_snowice = F_glob * (exp(-lambda_snow*state%snow_h) - exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h))
      |                                                                                                                                    1
Error: 'white_ice' at (1) is not a member of the 'modelstate' structure; did you mean 'white_ice_h'?
./src/strat_forcing.f90:366:132:

  366 |                F_ice     = F_glob * (exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h) - exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h))
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:366:132:

  366 |                F_ice     = F_glob * (exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h) - exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h))
      |                                                                                                                                    1
Error: 'snow' at (1) is not a member of the 'modelstate' structure; did you mean 'snow_h'?
./src/strat_forcing.f90:481:132:

  481 |          state%albedo_data(9,1:12) = [1.000_RK, 0.301_RK, 0.333_RK, 0.253_RK, 0.167_RK, 0.133_RK, 0.150_RK, 0.226_RK, 0.317_RK, 0.301_RK, 1.000_RK, 1.000_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:481:132:

  481 |          state%albedo_data(9,1:12) = [1.000_RK, 0.301_RK, 0.333_RK, 0.253_RK, 0.167_RK, 0.133_RK, 0.150_RK, 0.226_RK, 0.317_RK, 0.301_RK, 1.000_RK, 1.000_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:482:132:

  482 |          state%albedo_data(8,1:12) = [0.301_RK, 0.337_RK, 0.266_RK, 0.178_RK, 0.138_RK, 0.123_RK, 0.132_RK, 0.163_RK, 0.238_RK, 0.329_RK, 0.301_RK, 1.000_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:482:132:

  482 |          state%albedo_data(8,1:12) = [0.301_RK, 0.337_RK, 0.266_RK, 0.178_RK, 0.138_RK, 0.123_RK, 0.132_RK, 0.163_RK, 0.238_RK, 0.329_RK, 0.301_RK, 1.000_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:483:132:

  483 |          state%albedo_data(7,1:12) = [0.340_RK, 0.281_RK, 0.185_RK, 0.122_RK, 0.099_RK, 0.095_RK, 0.097_RK, 0.113_RK, 0.163_RK, 0.254_RK, 0.336_RK, 0.325_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:483:132:

  483 |          state%albedo_data(7,1:12) = [0.340_RK, 0.281_RK, 0.185_RK, 0.122_RK, 0.099_RK, 0.095_RK, 0.097_RK, 0.113_RK, 0.163_RK, 0.254_RK, 0.336_RK, 0.325_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:484:132:

  484 |          state%albedo_data(6,1:12) = [0.263_RK, 0.193_RK, 0.127_RK, 0.093_RK, 0.080_RK, 0.077_RK, 0.079_RK, 0.088_RK, 0.114_RK, 0.174_RK, 0.249_RK, 0.294_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:484:132:

  484 |          state%albedo_data(6,1:12) = [0.263_RK, 0.193_RK, 0.127_RK, 0.093_RK, 0.080_RK, 0.077_RK, 0.079_RK, 0.088_RK, 0.114_RK, 0.174_RK, 0.249_RK, 0.294_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:485:132:

  485 |          state%albedo_data(5,1:12) = [0.178_RK, 0.131_RK, 0.095_RK, 0.077_RK, 0.071_RK, 0.070_RK, 0.070_RK, 0.075_RK, 0.088_RK, 0.120_RK, 0.169_RK, 0.198_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:485:132:

  485 |          state%albedo_data(5,1:12) = [0.178_RK, 0.131_RK, 0.095_RK, 0.077_RK, 0.071_RK, 0.070_RK, 0.070_RK, 0.075_RK, 0.088_RK, 0.120_RK, 0.169_RK, 0.198_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:486:132:

  486 |          state%albedo_data(4,1:12) = [0.121_RK, 0.097_RK, 0.078_RK, 0.069_RK, 0.066_RK, 0.065_RK, 0.066_RK, 0.068_RK, 0.075_RK, 0.091_RK, 0.116_RK, 0.132_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:486:132:

  486 |          state%albedo_data(4,1:12) = [0.121_RK, 0.097_RK, 0.078_RK, 0.069_RK, 0.066_RK, 0.065_RK, 0.066_RK, 0.068_RK, 0.075_RK, 0.091_RK, 0.116_RK, 0.132_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:487:132:

  487 |          state%albedo_data(3,1:12) = [0.091_RK, 0.079_RK, 0.070_RK, 0.065_RK, 0.064_RK, 0.064_RK, 0.064_RK, 0.064_RK, 0.068_RK, 0.076_RK, 0.089_RK, 0.097_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:487:132:

  487 |          state%albedo_data(3,1:12) = [0.091_RK, 0.079_RK, 0.070_RK, 0.065_RK, 0.064_RK, 0.064_RK, 0.064_RK, 0.064_RK, 0.068_RK, 0.076_RK, 0.089_RK, 0.097_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:488:132:

  488 |          state%albedo_data(2,1:12) = [0.076_RK, 0.070_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.064_RK, 0.063_RK, 0.063_RK, 0.064_RK, 0.069_RK, 0.075_RK, 0.079_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:488:132:

  488 |          state%albedo_data(2,1:12) = [0.076_RK, 0.070_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.064_RK, 0.063_RK, 0.063_RK, 0.064_RK, 0.069_RK, 0.075_RK, 0.079_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:489:132:

  489 |          state%albedo_data(1,1:12) = [0.069_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.066_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.068_RK, 0.070_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:489:132:

  489 |          state%albedo_data(1,1:12) = [0.069_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.066_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.068_RK, 0.070_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:514:132:

  514 |          state%albedo_data(9,1:12) = [0.150_RK, 0.226_RK, 0.317_RK, 0.301_RK, 1.000_RK, 1.000_RK, 1.000_RK, 0.301_RK, 0.333_RK, 0.253_RK, 0.167_RK, 0.133_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:514:132:

  514 |          state%albedo_data(9,1:12) = [0.150_RK, 0.226_RK, 0.317_RK, 0.301_RK, 1.000_RK, 1.000_RK, 1.000_RK, 0.301_RK, 0.333_RK, 0.253_RK, 0.167_RK, 0.133_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:515:132:

  515 |          state%albedo_data(8,1:12) = [0.132_RK, 0.163_RK, 0.238_RK, 0.329_RK, 0.301_RK, 1.000_RK, 0.301_RK, 0.337_RK, 0.266_RK, 0.178_RK, 0.138_RK, 0.123_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:515:132:

  515 |          state%albedo_data(8,1:12) = [0.132_RK, 0.163_RK, 0.238_RK, 0.329_RK, 0.301_RK, 1.000_RK, 0.301_RK, 0.337_RK, 0.266_RK, 0.178_RK, 0.138_RK, 0.123_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:516:132:

  516 |          state%albedo_data(7,1:12) = [0.097_RK, 0.113_RK, 0.163_RK, 0.254_RK, 0.336_RK, 0.325_RK, 0.340_RK, 0.281_RK, 0.185_RK, 0.122_RK, 0.099_RK, 0.095_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:516:132:

  516 |          state%albedo_data(7,1:12) = [0.097_RK, 0.113_RK, 0.163_RK, 0.254_RK, 0.336_RK, 0.325_RK, 0.340_RK, 0.281_RK, 0.185_RK, 0.122_RK, 0.099_RK, 0.095_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:517:132:

  517 |          state%albedo_data(6,1:12) = [0.079_RK, 0.088_RK, 0.114_RK, 0.174_RK, 0.249_RK, 0.294_RK, 0.263_RK, 0.193_RK, 0.127_RK, 0.093_RK, 0.080_RK, 0.077_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:517:132:

  517 |          state%albedo_data(6,1:12) = [0.079_RK, 0.088_RK, 0.114_RK, 0.174_RK, 0.249_RK, 0.294_RK, 0.263_RK, 0.193_RK, 0.127_RK, 0.093_RK, 0.080_RK, 0.077_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:518:132:

  518 |          state%albedo_data(5,1:12) = [0.070_RK, 0.075_RK, 0.088_RK, 0.120_RK, 0.169_RK, 0.198_RK, 0.178_RK, 0.131_RK, 0.095_RK, 0.077_RK, 0.071_RK, 0.070_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:518:132:

  518 |          state%albedo_data(5,1:12) = [0.070_RK, 0.075_RK, 0.088_RK, 0.120_RK, 0.169_RK, 0.198_RK, 0.178_RK, 0.131_RK, 0.095_RK, 0.077_RK, 0.071_RK, 0.070_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:519:132:

  519 |          state%albedo_data(4,1:12) = [0.066_RK, 0.068_RK, 0.075_RK, 0.091_RK, 0.116_RK, 0.132_RK, 0.121_RK, 0.097_RK, 0.078_RK, 0.069_RK, 0.066_RK, 0.065_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:519:132:

  519 |          state%albedo_data(4,1:12) = [0.066_RK, 0.068_RK, 0.075_RK, 0.091_RK, 0.116_RK, 0.132_RK, 0.121_RK, 0.097_RK, 0.078_RK, 0.069_RK, 0.066_RK, 0.065_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:520:132:

  520 |          state%albedo_data(3,1:12) = [0.064_RK, 0.064_RK, 0.068_RK, 0.076_RK, 0.089_RK, 0.097_RK, 0.091_RK, 0.079_RK, 0.070_RK, 0.065_RK, 0.064_RK, 0.064_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:520:132:

  520 |          state%albedo_data(3,1:12) = [0.064_RK, 0.064_RK, 0.068_RK, 0.076_RK, 0.089_RK, 0.097_RK, 0.091_RK, 0.079_RK, 0.070_RK, 0.065_RK, 0.064_RK, 0.064_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:521:132:

  521 |          state%albedo_data(2,1:12) = [0.063_RK, 0.063_RK, 0.064_RK, 0.069_RK, 0.075_RK, 0.079_RK, 0.076_RK, 0.070_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.064_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:521:132:

  521 |          state%albedo_data(2,1:12) = [0.063_RK, 0.063_RK, 0.064_RK, 0.069_RK, 0.075_RK, 0.079_RK, 0.076_RK, 0.070_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.064_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:522:132:

  522 |          state%albedo_data(1,1:12) = [0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.068_RK, 0.070_RK, 0.069_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.066_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:522:132:

  522 |          state%albedo_data(1,1:12) = [0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.068_RK, 0.070_RK, 0.069_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.066_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
f951: some warnings being treated as errors

./src/strat_forcing.f90:47:132:

   47 |       if(self%cfg%snow_model == 1) call warn('The snow module is turned on. This module needs precipitation data, note that the last column in the forcing file will be interpreted as precipitation.')
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:47:45:

   47 |       if(self%cfg%snow_model == 1) call warn('The snow module is turned on. This module needs precipitation data, note that the last column in the forcing file will be interpreted as precipitation.')
      |                                             1
Error: Missing ')' in statement at or before (1)
./src/strat_forcing.f90:281:132:

  281 |                fu = sqrt((2.7_RK*max(0.0_RK,(T_surf-state%T_atm)/(1 - 0.378_RK*Vap_atm/param%p_air))**0.333_RK)**2 + (0.6072_RK*3.1_RK*state%uv10)**2)
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:281:132:

  281 |                fu = sqrt((2.7_RK*max(0.0_RK,(T_surf-state%T_atm)/(1 - 0.378_RK*Vap_atm/param%p_air))**0.333_RK)**2 + (0.6072_RK*3.1_RK*state%uv10)**2)
      |                                                                                                                                    1
Error: Missing kind-parameter at (1)
./src/strat_forcing.f90:358:132:

  358 |                state%heat = F_glob * exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h) * param%beta_sol
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:358:132:

  358 |                state%heat = F_glob * exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h) * param%beta_sol
      |                                                                                                                                    1
Error: Syntax error in argument list at (1)
./src/strat_forcing.f90:359:132:

  359 |                state%rad0 = F_glob * exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h) * (1 - param%beta_sol)
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:359:132:

  359 |                state%rad0 = F_glob * exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h) * (1 - param%beta_sol)
      |                                                                                                                                    1
Error: Syntax error in argument list at (1)
./src/strat_forcing.f90:365:132:

  365 |                F_snowice = F_glob * (exp(-lambda_snow*state%snow_h) - exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h))
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:365:132:

  365 |                F_snowice = F_glob * (exp(-lambda_snow*state%snow_h) - exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h))
      |                                                                                                                                    1
Error: 'white_ice' at (1) is not a member of the 'modelstate' structure; did you mean 'white_ice_h'?
./src/strat_forcing.f90:366:132:

  366 |                F_ice     = F_glob * (exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h) - exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h))
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:366:132:

  366 |                F_ice     = F_glob * (exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h) - exp(-lambda_snow*state%snow_h - lambda_snowice*state%white_ice_h - lambda_ice*state%black_ice_h))
      |                                                                                                                                    1
Error: 'snow' at (1) is not a member of the 'modelstate' structure; did you mean 'snow_h'?
./src/strat_forcing.f90:481:132:

  481 |          state%albedo_data(9,1:12) = [1.000_RK, 0.301_RK, 0.333_RK, 0.253_RK, 0.167_RK, 0.133_RK, 0.150_RK, 0.226_RK, 0.317_RK, 0.301_RK, 1.000_RK, 1.000_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:481:132:

  481 |          state%albedo_data(9,1:12) = [1.000_RK, 0.301_RK, 0.333_RK, 0.253_RK, 0.167_RK, 0.133_RK, 0.150_RK, 0.226_RK, 0.317_RK, 0.301_RK, 1.000_RK, 1.000_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:482:132:

  482 |          state%albedo_data(8,1:12) = [0.301_RK, 0.337_RK, 0.266_RK, 0.178_RK, 0.138_RK, 0.123_RK, 0.132_RK, 0.163_RK, 0.238_RK, 0.329_RK, 0.301_RK, 1.000_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:482:132:

  482 |          state%albedo_data(8,1:12) = [0.301_RK, 0.337_RK, 0.266_RK, 0.178_RK, 0.138_RK, 0.123_RK, 0.132_RK, 0.163_RK, 0.238_RK, 0.329_RK, 0.301_RK, 1.000_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:483:132:

  483 |          state%albedo_data(7,1:12) = [0.340_RK, 0.281_RK, 0.185_RK, 0.122_RK, 0.099_RK, 0.095_RK, 0.097_RK, 0.113_RK, 0.163_RK, 0.254_RK, 0.336_RK, 0.325_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:483:132:

  483 |          state%albedo_data(7,1:12) = [0.340_RK, 0.281_RK, 0.185_RK, 0.122_RK, 0.099_RK, 0.095_RK, 0.097_RK, 0.113_RK, 0.163_RK, 0.254_RK, 0.336_RK, 0.325_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:484:132:

  484 |          state%albedo_data(6,1:12) = [0.263_RK, 0.193_RK, 0.127_RK, 0.093_RK, 0.080_RK, 0.077_RK, 0.079_RK, 0.088_RK, 0.114_RK, 0.174_RK, 0.249_RK, 0.294_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:484:132:

  484 |          state%albedo_data(6,1:12) = [0.263_RK, 0.193_RK, 0.127_RK, 0.093_RK, 0.080_RK, 0.077_RK, 0.079_RK, 0.088_RK, 0.114_RK, 0.174_RK, 0.249_RK, 0.294_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:485:132:

  485 |          state%albedo_data(5,1:12) = [0.178_RK, 0.131_RK, 0.095_RK, 0.077_RK, 0.071_RK, 0.070_RK, 0.070_RK, 0.075_RK, 0.088_RK, 0.120_RK, 0.169_RK, 0.198_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:485:132:

  485 |          state%albedo_data(5,1:12) = [0.178_RK, 0.131_RK, 0.095_RK, 0.077_RK, 0.071_RK, 0.070_RK, 0.070_RK, 0.075_RK, 0.088_RK, 0.120_RK, 0.169_RK, 0.198_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:486:132:

  486 |          state%albedo_data(4,1:12) = [0.121_RK, 0.097_RK, 0.078_RK, 0.069_RK, 0.066_RK, 0.065_RK, 0.066_RK, 0.068_RK, 0.075_RK, 0.091_RK, 0.116_RK, 0.132_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:486:132:

  486 |          state%albedo_data(4,1:12) = [0.121_RK, 0.097_RK, 0.078_RK, 0.069_RK, 0.066_RK, 0.065_RK, 0.066_RK, 0.068_RK, 0.075_RK, 0.091_RK, 0.116_RK, 0.132_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:487:132:

  487 |          state%albedo_data(3,1:12) = [0.091_RK, 0.079_RK, 0.070_RK, 0.065_RK, 0.064_RK, 0.064_RK, 0.064_RK, 0.064_RK, 0.068_RK, 0.076_RK, 0.089_RK, 0.097_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:487:132:

  487 |          state%albedo_data(3,1:12) = [0.091_RK, 0.079_RK, 0.070_RK, 0.065_RK, 0.064_RK, 0.064_RK, 0.064_RK, 0.064_RK, 0.068_RK, 0.076_RK, 0.089_RK, 0.097_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:488:132:

  488 |          state%albedo_data(2,1:12) = [0.076_RK, 0.070_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.064_RK, 0.063_RK, 0.063_RK, 0.064_RK, 0.069_RK, 0.075_RK, 0.079_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:488:132:

  488 |          state%albedo_data(2,1:12) = [0.076_RK, 0.070_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.064_RK, 0.063_RK, 0.063_RK, 0.064_RK, 0.069_RK, 0.075_RK, 0.079_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:489:132:

  489 |          state%albedo_data(1,1:12) = [0.069_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.066_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.068_RK, 0.070_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:489:132:

  489 |          state%albedo_data(1,1:12) = [0.069_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.066_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.068_RK, 0.070_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:514:132:

  514 |          state%albedo_data(9,1:12) = [0.150_RK, 0.226_RK, 0.317_RK, 0.301_RK, 1.000_RK, 1.000_RK, 1.000_RK, 0.301_RK, 0.333_RK, 0.253_RK, 0.167_RK, 0.133_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:514:132:

  514 |          state%albedo_data(9,1:12) = [0.150_RK, 0.226_RK, 0.317_RK, 0.301_RK, 1.000_RK, 1.000_RK, 1.000_RK, 0.301_RK, 0.333_RK, 0.253_RK, 0.167_RK, 0.133_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:515:132:

  515 |          state%albedo_data(8,1:12) = [0.132_RK, 0.163_RK, 0.238_RK, 0.329_RK, 0.301_RK, 1.000_RK, 0.301_RK, 0.337_RK, 0.266_RK, 0.178_RK, 0.138_RK, 0.123_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:515:132:

  515 |          state%albedo_data(8,1:12) = [0.132_RK, 0.163_RK, 0.238_RK, 0.329_RK, 0.301_RK, 1.000_RK, 0.301_RK, 0.337_RK, 0.266_RK, 0.178_RK, 0.138_RK, 0.123_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:516:132:

  516 |          state%albedo_data(7,1:12) = [0.097_RK, 0.113_RK, 0.163_RK, 0.254_RK, 0.336_RK, 0.325_RK, 0.340_RK, 0.281_RK, 0.185_RK, 0.122_RK, 0.099_RK, 0.095_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:516:132:

  516 |          state%albedo_data(7,1:12) = [0.097_RK, 0.113_RK, 0.163_RK, 0.254_RK, 0.336_RK, 0.325_RK, 0.340_RK, 0.281_RK, 0.185_RK, 0.122_RK, 0.099_RK, 0.095_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:517:132:

  517 |          state%albedo_data(6,1:12) = [0.079_RK, 0.088_RK, 0.114_RK, 0.174_RK, 0.249_RK, 0.294_RK, 0.263_RK, 0.193_RK, 0.127_RK, 0.093_RK, 0.080_RK, 0.077_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:517:132:

  517 |          state%albedo_data(6,1:12) = [0.079_RK, 0.088_RK, 0.114_RK, 0.174_RK, 0.249_RK, 0.294_RK, 0.263_RK, 0.193_RK, 0.127_RK, 0.093_RK, 0.080_RK, 0.077_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:518:132:

  518 |          state%albedo_data(5,1:12) = [0.070_RK, 0.075_RK, 0.088_RK, 0.120_RK, 0.169_RK, 0.198_RK, 0.178_RK, 0.131_RK, 0.095_RK, 0.077_RK, 0.071_RK, 0.070_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:518:132:

  518 |          state%albedo_data(5,1:12) = [0.070_RK, 0.075_RK, 0.088_RK, 0.120_RK, 0.169_RK, 0.198_RK, 0.178_RK, 0.131_RK, 0.095_RK, 0.077_RK, 0.071_RK, 0.070_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:519:132:

  519 |          state%albedo_data(4,1:12) = [0.066_RK, 0.068_RK, 0.075_RK, 0.091_RK, 0.116_RK, 0.132_RK, 0.121_RK, 0.097_RK, 0.078_RK, 0.069_RK, 0.066_RK, 0.065_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:519:132:

  519 |          state%albedo_data(4,1:12) = [0.066_RK, 0.068_RK, 0.075_RK, 0.091_RK, 0.116_RK, 0.132_RK, 0.121_RK, 0.097_RK, 0.078_RK, 0.069_RK, 0.066_RK, 0.065_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:520:132:

  520 |          state%albedo_data(3,1:12) = [0.064_RK, 0.064_RK, 0.068_RK, 0.076_RK, 0.089_RK, 0.097_RK, 0.091_RK, 0.079_RK, 0.070_RK, 0.065_RK, 0.064_RK, 0.064_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:520:132:

  520 |          state%albedo_data(3,1:12) = [0.064_RK, 0.064_RK, 0.068_RK, 0.076_RK, 0.089_RK, 0.097_RK, 0.091_RK, 0.079_RK, 0.070_RK, 0.065_RK, 0.064_RK, 0.064_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:521:132:

  521 |          state%albedo_data(2,1:12) = [0.063_RK, 0.063_RK, 0.064_RK, 0.069_RK, 0.075_RK, 0.079_RK, 0.076_RK, 0.070_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.064_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:521:132:

  521 |          state%albedo_data(2,1:12) = [0.063_RK, 0.063_RK, 0.064_RK, 0.069_RK, 0.075_RK, 0.079_RK, 0.076_RK, 0.070_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.064_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
./src/strat_forcing.f90:522:132:

  522 |          state%albedo_data(1,1:12) = [0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.068_RK, 0.070_RK, 0.069_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.066_RK]
      |                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
./src/strat_forcing.f90:522:132:

  522 |          state%albedo_data(1,1:12) = [0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.068_RK, 0.070_RK, 0.069_RK, 0.065_RK, 0.063_RK, 0.063_RK, 0.065_RK, 0.066_RK]
      |                                                                                                                                    1
Error: Syntax error in array constructor at (1)
f951: some warnings being treated as errors
```

**Comment by Diftin** [comment]
For me there appear to be 3 possibilities:
- you are not using the right fobos file
=> make sure again that the right file (and only this one) is located in your build folder

- the compiler flags are not read and replaced by "-c" for some reason
=> I don't know what to do

- only the first compiler flag is read and the others are ignored
=> I would try some things like delete the whitespaces between the individual flags or put all flags (together) between "". Additional, you could remove the "-c" flag from the compiler flags to see which flag will be used during compilation in this case.

**Comment by d-vanzo** [comment]
To me it seems you are running the building command from the root folder and not inside the build folder.

**Comment by robertladwig** [comment]
Ahhhh gosh, yes - I'm so sorry for all the confusion. Yes, somehow I didn't even think about running FoBoS in build. Now it's working flawlessly and the executable was created.

Thank you both a lot!
